# Array（数组）
* rank

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a = a.reshape(1,-1)

In [8]:
a.shape

(1, 3)

In [9]:
a = np.array([1,2,3,4,5,6])

In [10]:
a = a.reshape(2,-1)

In [11]:
a.shape

(2, 3)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = a.reshape(-1,2)

In [14]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a[2,0]

5

In [16]:
a[2,0]=55

In [17]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

# zeros

In [18]:
a = np.zeros((2,3))

In [19]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
a = np.ones((2,3))

In [21]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# full

In [24]:
a = np.full((3,3),1)

In [25]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# eye

In [26]:
a = np.eye(3)

In [27]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## random.random

In [29]:
a = np.random.random((3,4))

In [30]:
a

array([[ 0.11292142,  0.49689869,  0.21044872,  0.61659777],
       [ 0.6996419 ,  0.07768928,  0.70277439,  0.32193145],
       [ 0.90320365,  0.71384183,  0.15750706,  0.68835683]])

# indexing

In [32]:
a = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [33]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [34]:
a[-2:][1:3]

array([[ 9, 10, 11, 12]])

In [35]:
a[1,-2]

7

In [36]:
a.shape

(3, 4)

In [41]:
b = a[-2:,1:3]

In [42]:
b

array([[ 6,  7],
       [10, 11]])

In [43]:
b.shape

(2, 2)

In [44]:
b = a[2,1:3]

In [45]:
b

array([10, 11])

In [46]:
b.shape

(2,)

In [47]:
b = a[1,2]

In [48]:
b

7

In [49]:
b.shape

()

In [50]:
b = a[2:3,1:3]

In [51]:
b

array([[10, 11]])

In [52]:
b.shape

(1, 2)

In [54]:
a[np.arange(3),1] +=10

In [55]:
np.arange(3,7)

array([3, 4, 5, 6])

In [56]:
np.arange(3)

array([0, 1, 2])

In [57]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [58]:
a[np.arange(3),[1,1,1]]+=10

In [59]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [61]:
a[[0,1,2],[1,1,1]]+=10

In [62]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [63]:
result_index = a>10

In [64]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]], dtype=bool)

In [65]:
a[result_index]

array([32, 36, 40, 11, 12])

In [66]:
a[a>10]

array([32, 36, 40, 11, 12])

# 元素的数据类型

In [67]:
a = np.array([1,2])

In [68]:
a.dtype

dtype('int64')

In [69]:
a = np.array([1.1,2.2])

In [70]:
a.dtype

dtype('float64')

In [71]:
a = np.array([1,2.2])

In [72]:
a.dtype

dtype('float64')

In [73]:
a = np.array([1.1,2.6])

In [74]:
a = np.array([1.1,2.6],dtype=np.int64)

In [75]:
a

array([1, 2])

In [76]:
a = np.array([1.1,2.6])

In [77]:
b = np.array(a,dtype=np.int64)

In [78]:
b

array([1, 2])

# 数学运算与常用函数

In [80]:
a = np.array([[1,2],
            [3,4]])

In [81]:
b = np.array([[5,6],
            [6,5]])

In [82]:
a+b

array([[6, 8],
       [9, 9]])

In [83]:
np.add(a,b)

array([[6, 8],
       [9, 9]])

In [84]:
a-b

array([[-4, -4],
       [-3, -1]])

In [85]:
np.subtract(a,b)

array([[-4, -4],
       [-3, -1]])

In [86]:
a*b

array([[ 5, 12],
       [18, 20]])

In [87]:
np.multiply(a,b)

array([[ 5, 12],
       [18, 20]])

In [88]:
a/b

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.8       ]])

In [89]:
np.divide(a,b)

array([[ 0.2       ,  0.33333333],
       [ 0.5       ,  0.8       ]])

In [90]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [91]:
a

array([[1, 2],
       [3, 4]])

In [92]:
b = np.array([[1,2,3],
             [4,5,6]])

In [94]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [95]:
np.dot(a,b)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [96]:
np.dot(b,a)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## 常用函数

In [97]:
a

array([[1, 2],
       [3, 4]])

In [98]:
np.sum(a)

10

In [99]:
np.sum(a,axis=0)

array([4, 6])

In [100]:
np.sum(a,axis=1)

array([3, 7])

### mean平均值

In [101]:
np.mean(a)

2.5

In [102]:
np.mean(a,axis=0)

array([ 2.,  3.])

In [103]:
np.mean(a,axis=1)

array([ 1.5,  3.5])

## uniform

In [104]:
np.random.uniform(3,4)

3.1554603064495317

In [107]:
np.random.uniform(1,100)

92.19367483707285

## tile

In [108]:
a

array([[1, 2],
       [3, 4]])

In [111]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [112]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [113]:
np.tile(a,(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

## argsort

In [116]:
a = np.array([[3,6,4,11],
            [5,10,1,3]])

In [118]:
a.argsort()

array([[0, 2, 1, 3],
       [2, 3, 0, 1]])

In [120]:
a.argsort(axis=0)  #每列从小到大排序

array([[0, 0, 1, 1],
       [1, 1, 0, 0]])

## 矩阵转置

In [121]:
a

array([[ 3,  6,  4, 11],
       [ 5, 10,  1,  3]])

In [122]:
a.T

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

In [123]:
np.transpose(a)

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

## 广播

In [124]:
a = np.array([[1,2,3],
             [2,3,4],
             [12,31,22],
             [2,2,2]])

In [125]:
b = np.array([1,2,3])

In [126]:
for i in range(4):
    a[i,:]+=b

In [127]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 33, 25],
       [ 3,  4,  5]])

In [128]:
a + np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])

In [129]:
a+b

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 35, 28],
       [ 4,  6,  8]])